server:
  port: 9090
spring:
  application:
    name: ORIVEWEBSITE-GATEWAY
  cloud:
    gateway:
      routes:
      - id: ORIVEWEBSITE-SERVICE
        uri: lb://ORIVEWEBSITE-SERVICE
        predicates:
        - Path=/careersgetjobAlerts/**,/journalsdetails/**,/landingpagepopup/**,/reachus/** 
      - id: INTERVIEW-SCHEDULER
        uri: lb://INTERVIEW-SCHEDULER
        predicates:
          - Path=/candidates/**,/interviews/**,/talents/**,/users/**     
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka            